version: '3'

volumes:
  spark_event_logs:

services:

  spark-image:
    build:
      context: .
      dockerfile: Dockerfile.sparksubmit
    image: spark-submit-image

  spark-history-server:
    image: spark-submit-image
    container_name: spark-history-server
    ports:
      - "18080:18080"
    volumes:
      - spark_event_logs:/event_log_directory
    command: [ "/usr/share/spark/sbin/start-history-server-and-wait.sh" ]

  spark-master:
    image: spark-submit-image
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark_event_logs:/event_log_directory
    command: [ "/usr/share/spark/sbin/start-master.sh" ]

  spark-worker-1:
    image: spark-submit-image
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    volumes:
      - spark_event_logs:/event_log_directory
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: [ "/usr/share/spark/sbin/start-worker.sh" ]

  spark-worker-2:
    image: spark-submit-image
    container_name: spark-worker-2
    ports:
      - "8082:8082"
    volumes:
      - spark_event_logs:/event_log_directory
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: [ "/usr/share/spark/sbin/start-worker.sh" ]

